##
# Copyright (c) KMG. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
##


site_name: 'Storage Benchmark Kit'
site_url: 'https://kmgowda.github.io/SBK/'
site_description: 'Documentation for SBK'

repo_url: 'https://github.com/kmgowda/SBK'
edit_uri: 'tree/master/documentation/src/docs'


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.highlight

nav:
  - SBK: 'https://github.com/kmgowda/SBK/blob/master/README.md'
  - SBK RAM: 'https://github.com/kmgowda/SBK/blob/master/sbk-ram/README.md'
  - SBK GEM: 'https://github.com/kmgowda/SBK/blob/master/sbk-gem/README.md'
  - SBK GEM YAL: 'https://github.com/kmgowda/SBK/blob/master/sbk-gem-yal/README.md'
